namespace Knowledge.Core.Models;

/// <summary>Structured metadata generated by the LLM for a single chunk.</summary>
public class ChunkMetadata
{
    public string Summary { get; set; } = string.Empty;

    public List<string> Tags { get; set; } = new();

    public List<string> Keywords { get; set; } = new();

    public List<string> Entities { get; set; } = new();
}
